Admin API
maggiemmae/TTYC pull request #3
Opened 2022-08-22 21:01 UTC by maggiemmae

2022-08-23 10:30 UTC, dandreyew requested changes

2022-08-23 10:30 UTC, dandreyew commented on TTYC.Application/Products/AddProduct/AddProductCommand.cs
> +        public int Price { get; set; }
What if my product costs 23 bucks 34 cents?

2022-08-23 10:30 UTC, dandreyew commented on TTYC.Application/Users/Queries/ValidatePassword/ValidatePasswordHandler.cs
> +
no need in a line break here

2022-08-23 10:30 UTC, dandreyew commented on TTYC.ClientAPI/Controllers/AccountController.cs
> +			var responce = await mediatr.Send(command);
response

2022-08-23 10:30 UTC, dandreyew commented on TTYC.ClientAPI/Controllers/ProductController.cs
> +		/// Adds product.
Fix tabs

2022-08-23 10:30 UTC, dandreyew commented on TTYC.ClientAPI/Controllers/ProductController.cs
> +		/// Gets paged list of products.
fix tabs

2022-08-23 10:30 UTC, dandreyew commented on TTYC.ClientAPI/Controllers/ProductController.cs
> +		/// Gets product by id.
fix tabs

2022-08-23 10:30 UTC, dandreyew commented on TTYC.ClientAPI/Controllers/UserController.cs
> +		private readonly ISender mediatr;
Fix tabs

2022-08-23 10:30 UTC, dandreyew commented on TTYC.ClientAPI/Program.cs
> +			{
fix tabs

2022-08-23 10:30 UTC, dandreyew commented on TTYC.Constants/ConfigurationConstants.cs
>  		public const string DefaultConnection = "DefaultConnection";
fix formatting

2022-08-23 10:30 UTC, dandreyew commented on TTYC.Domain/User.cs
> +		public Guid Id { get; set; }
Fix tabs

2022-08-23 10:30 UTC, dandreyew commented on TTYC.Domain/UserProfile.cs
> +		public string Name { get; set; }
Fix tabs

2022-08-23 10:30 UTC, dandreyew commented on TTYC.IdentityServer/Config.cs
> +		public static ClientOptions ClientOptions { get; set; } = new ClientOptions();
Fix tabs

2022-08-23 10:30 UTC, dandreyew commented on TTYC.IdentityServer/CustomProfileService.cs
> +
No need in a line break

2022-08-23 10:30 UTC, dandreyew commented on TTYC.IdentityServer/ResourceOwnerPasswordValidator.cs
> +			var query = new ValidatePasswordQuery()
fix tabs

2022-08-23 10:30 UTC, dandreyew commented on TTYC.Persistence/ApplicationDbContext.cs
>  		public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
Fix tabs

2022-08-23 10:37 UTC, dandreyew requested changes

2022-08-23 10:37 UTC, dandreyew commented on TTYC.Application/Products/GetProductsList/GetProductsListQuery.cs
> +        const int maxPageSize = 50;
Fix field order

2022-08-23 11:03 UTC, dandreyew requested changes

2022-08-23 11:03 UTC, dandreyew commented on TTYC.ClientAPI/Controllers/ProductController.cs
> +        public async Task<IActionResult> GetProduct(Guid id)
Attribure missing [FromRoute]

2022-08-24 11:43 UTC, dandreyew requested changes

2022-08-24 11:43 UTC, dandreyew commented on TTYC.Application/Profiles/MapperProfile.cs
> +            CreateMap<User, UserInfrastructure>().ForMember(x => x.Status, opt => opt.MapFrom(x => x.LockoutEnd < DateTime.UtcNow ? "Active" : "Blocked"));
Move "Active" and "Blocked" to constants. Better to create a separate file for them

2022-08-24 11:43 UTC, dandreyew commented on TTYC.Application/Stores/AddProductToStore/AddProductToStoreHandler.cs
> +                .Single(p => p.Id == command.ProductId);
Why do we use async method for stores and a sync method for the same situation with product?

2022-08-24 11:43 UTC, dandreyew commented on TTYC.Application/Stores/AddProductToStore/AddProductToStoreHandler.cs
> +            store.Products.Add(product);
You used AddAsync in AddStoreHandler. Regarding Add function the Async overload does not make much of sense, because it does not actually contact the database yet. I think this was added to write repositories without a need to map async Tasks to sync voids. But you have to pick one method to use in all similar situations.

2022-08-24 11:43 UTC, dandreyew commented on TTYC.Application/Stores/AddStore/AddStoreCommand.cs
> +        public string Name { get; set; }
I think the main parameter for the store is its location

2022-08-24 11:43 UTC, dandreyew commented on TTYC.Application/Stores/EditStore/EditStoreHandler.cs
> +            var store = await dbContext.Stores.FirstOrDefaultAsync(x => x.Id == command.Id, cancellationToken);
In the same situations you use Single and FirstOrDefault. You gotta pick one of them

2022-08-24 11:43 UTC, dandreyew commented on TTYC.Application/Stores/GetStoresList/GetStoresListHandler.cs
> +                throw new NullReferenceException("Stores not found");
That is not an error. If you just started the app and you have not added any stores yet this is just an empty list of stores or 204 No Content. But that is definetly not an error

2022-08-24 11:43 UTC, dandreyew commented on TTYC.Application/Users/Commands/AddProfile/AddProfileHandler.cs
> +                        FlatNumber = command.Address.HouseNumber,
I see a bug here. And why not use automapper?

2022-08-24 11:43 UTC, dandreyew commented on TTYC.ClientAPI/Controllers/ProfileController.cs
> +        public async Task<UserProfile> GetUserProfile()
Task< IActionResult >

2022-08-24 11:43 UTC, dandreyew commented on TTYC.Application/Users/Commands/BlockUser/BlockUserCommand.cs
> +        public int Hours { get; set; }
I think block for some time period is better.

2022-08-24 11:43 UTC, dandreyew commented on TTYC.Application/Users/Queries/ValidatePassword/ValidatePasswordQuery.cs
> +    public class ValidatePasswordQuery : IRequest<User>
You validate a password without passing a password. It looks more like GetUserQuery to me

2022-08-24 11:43 UTC, dandreyew commented on TTYC.ClientAPI/Controllers/UserController.cs
> +}
![image](https://user-images.githubusercontent.com/46454404/186408603-624ccc74-5618-4b81-a483-e6242e6beb18.png)
Watch this please

2022-08-24 11:43 UTC, dandreyew commented on TTYC.ClientAPI/Program.cs
> +                TokenUrl = new Uri("https://localhost:7294/connect/token"),
https://localhost:7294 should be in appsettings

2022-08-24 11:43 UTC, dandreyew commented on TTYC.ClientAPI/Program.cs
> +        options.Authority = "https://localhost:7294";
Appsettings

2022-08-24 11:43 UTC, dandreyew commented on TTYC.Domain/Address.cs
> +        public Guid UserId { get; set; }
ProfileId? UserProfileId? Not clear what this Id is for

2022-08-24 11:43 UTC, dandreyew commented on TTYC.IdentityServer/CustomProfileService.cs
> +        public Task IsActiveAsync(IsActiveContext context)
Looks like a place where you actually validate the LockoutEnd.
@lALTAIRl Please confirm

2022-08-24 11:43 UTC, dandreyew commented on TTYC.IdentityServer/Program.cs
> +app.UseCors("CorsPolicy");
Constants

2022-08-24 12:06 UTC, maggiemmae commented on TTYC.Domain/Address.cs
> +        public Guid UserId { get; set; }
For user id

2022-08-24 12:17 UTC, dandreyew commented on TTYC.Domain/Address.cs
> +        public Guid UserId { get; set; }
But we dont have a User refence. And why is it specially grouped with UserProfile?

2022-08-24 18:19 UTC, dandreyew approved these changes

2022-08-24 18:20 UTC, merged